Improve "missing variable name" error message
This fixes VIPROMA-108 by changing the message to:

    Error: In "connections" section: Missing or empty variable
    identifier (should be on the format "slave.var")